name: NCBI Data Ingest

on:
  push:
    paths:
      - .github/workflows/eutility_query_to_graph.yml
  workflow_dispatch:
  schedule:
    - cron: '*/360 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use local my-action
      uses: ./    # Uses an action in the root directory
    # - name: Run bash
    #   run: bash ./ace2_related_3d_gene_structure.sh
    - name: test
      run: /usr/bin/esearch --help