name: NCBI Data Ingest

on:
  push:
    paths:
      - .github/workflows/eutility_query_to_graph.yml
  workflow_dispatch:
  schedule:
    - cron: '* 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Use local my-action
      uses: ./    # Uses an action in the root directory

    - name: check for changes
      run: |
        if git diff --exit-code; then
          echo "changes_exist=true" >> $GITHUB_ENV
        else
          echo "changes_exist=false" >> $GITHUB_ENV
        fi

    - name: Commit files
      if: ${{ $GITHUB_ENV.changes_exist == 'true' }}
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add newest_structure.json
        git commit -m "Add changes" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
