name: NCBI Data Ingest

on:
  push:
    paths:
      - .github/workflows/eutility_query_to_graph.yml
  workflow_dispatch:
  schedule:
    - cron: '* 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Use local my-action
      uses: ./    # Uses an action in the root directory

    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11

    - name: Commit files
      if: steps.changes.outputs.changed == 1
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add newest_structure.json
        git commit -m "Add changes" -a
        
    - name: Push changes
      if: steps.changes.outputs.changed == 1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
